[[constraint]]
  name = "github.com/davidminor/gorand"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.*"

[[constraint]]
  name = "github.com/seehuhn/mt19937"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.*"

[[constraint]]
  name = "github.com/spiegel-im-spiegel/gocli"
  version = "0.3.*"

[prune]
  go-tests = true
  unused-packages = true
